name: CSM Bot Scheduler

on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 2 * * *'
    - cron: '0 6 * * *'
    - cron: '0 10 * * *'
    - cron: '0 14 * * *'

  workflow_dispatch:

jobs:
  run-csm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CSM Bot (single broadcast)
        env:
          TELEGRAM_BOT_TOKEN: "8781053968:AAE2f3-DtO7Cl6r41lGkZ97QqKPlu6y2GjE"
          TELEGRAM_CHAT_ID: "-1003786027315"  #MCROTRADES
          TELEGRAM_CHAT_ID_2: ""
        run: python currency_strength_meter_v10_yfinance.py --once
